target = VALID_2010_paper

source = $(target).tex
latex_cmd = pdflatex
counter_file = build_counter.txt
pdf_file = $(target).pdf
bibtex_file = consolidated_bibtex_file.bib
bibtex_source = ../bibtex/consolidated_bibtex_source.bib

graphics = simple-CDS.pdf complex-CDS.pdf R-prime-context-plus-N-prime.pdf thesis-question.pdf

temporary_files = *.log *.aux *.out *.idx *.ilg *.blg *.bbl *.nav \
	*.snm *.ind *.lof *.lot *.toc .pdf *.dvi

include ../Makefiles/git1.mk

all: $(pdf_file)

include ../Makefiles/git2.mk

$(bibtex_file): $(bibtex_source)
	cp $(bibtex_source) $(bibtex_file)

simple-CDS.pdf: simple-CDS.svg
	@echo "The PDF of $@ is generated by Inkscape."

complex-CDS.pdf: complex-CDS.svg
	@echo "The PDF of $@ is generated by Inkscape."

R-prime-context-plus-N-prime.pdf: R-prime-context-plus-N-prime.svg
	@echo "The PDF of $@ is generated by Inkscape."

thesis-question.pdf: thesis-question.svg
	@echo "The PDF of $@ is generated by Inkscape."

$(pdf_file): $(source) Makefile $(bibtex_file) $(graphics)
	@echo $$(($$(cat $(counter_file)) + 1)) > $(counter_file)
	$(latex_cmd) $(source)
	bibtex $(target)
	if (grep "Warning" $(target).blg > /dev/null ) then false ; fi
	while ( \
		$(latex_cmd) $(target) ; \
		grep "Rerun to get" $(target).log > /dev/null \
	) do true ; done
	chmod a-x,a+r $(pdf_file)
	@echo "Build `cat $(counter_file)`"

vi:
	vi $(source)

spell:
	aspell --lang=EN_GB -t check $(source)
	aspell --lang=en_GB check $(documentation)

clean:
	rm -f $(temporary_files) $(documentation).bak

allclean: clean
	rm -f $(pdf_file) *.bbl

bibtex:
	(cd ../bibtex/ && make vi)

notes:
	(cd ../notes/ && make notes)

